export const metadata = {
  title: 'Kanban Clint',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body style={{ background: '#eae3d0' }}>
        {children}
      </body>
    </html>
  )
}
